name: kappa_framework
description: "A new Flutter framework for Web with Clean Architecture."
version: 0.0.1

environment:
  sdk: ^3.11.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_bloc: ^8.1.5
  easy_localization: ^3.0.7
  path_provider: ^2.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.7
  args: ^2.4.2

flutter:
  uses-material-design: true
